package com.zhilian.rf_qims.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zhilian.rf_qims.entity.SamplePage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SAMPLE_PAGE".
*/
public class SamplePageDao extends AbstractDao<SamplePage, Long> {

    public static final String TABLENAME = "SAMPLE_PAGE";

    /**
     * Properties of entity SamplePage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Pid = new Property(1, int.class, "pid", false, "PID");
        public final static Property Samplepage = new Property(2, int.class, "samplepage", false, "SAMPLEPAGE");
    }


    public SamplePageDao(DaoConfig config) {
        super(config);
    }
    
    public SamplePageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SAMPLE_PAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"PID\" INTEGER NOT NULL ," + // 1: pid
                "\"SAMPLEPAGE\" INTEGER NOT NULL );"); // 2: samplepage
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SAMPLE_PAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SamplePage entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getPid());
        stmt.bindLong(3, entity.getSamplepage());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SamplePage entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getPid());
        stmt.bindLong(3, entity.getSamplepage());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public SamplePage readEntity(Cursor cursor, int offset) {
        SamplePage entity = new SamplePage( //
            cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // pid
            cursor.getInt(offset + 2) // samplepage
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SamplePage entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setPid(cursor.getInt(offset + 1));
        entity.setSamplepage(cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SamplePage entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SamplePage entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SamplePage entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
