package com.zhilian.rf_qims.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zhilian.rf_qims.entity.ProQuality;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRO_QUALITY".
*/
public class ProQualityDao extends AbstractDao<ProQuality, Long> {

    public static final String TABLENAME = "PRO_QUALITY";

    /**
     * Properties of entity ProQuality.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Rid = new Property(1, long.class, "rid", false, "RID");
        public final static Property Gbhd = new Property(2, String.class, "gbhd", false, "GBHD");
        public final static Property Gjfb = new Property(3, String.class, "gjfb", false, "GJFB");
        public final static Property Hltqd = new Property(4, String.class, "hltqd", false, "HLTQD");
        public final static Property Jgzl = new Property(5, String.class, "jgzl", false, "JGZL");
        public final static Property Qmzl = new Property(6, String.class, "qmzl", false, "QMZL");
        public final static Property Xbm = new Property(7, String.class, "xbm", false, "XBM");
    }


    public ProQualityDao(DaoConfig config) {
        super(config);
    }
    
    public ProQualityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRO_QUALITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"RID\" INTEGER NOT NULL ," + // 1: rid
                "\"GBHD\" TEXT," + // 2: gbhd
                "\"GJFB\" TEXT," + // 3: gjfb
                "\"HLTQD\" TEXT," + // 4: hltqd
                "\"JGZL\" TEXT," + // 5: jgzl
                "\"QMZL\" TEXT," + // 6: qmzl
                "\"XBM\" TEXT);"); // 7: xbm
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRO_QUALITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ProQuality entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getRid());
 
        String gbhd = entity.getGbhd();
        if (gbhd != null) {
            stmt.bindString(3, gbhd);
        }
 
        String gjfb = entity.getGjfb();
        if (gjfb != null) {
            stmt.bindString(4, gjfb);
        }
 
        String hltqd = entity.getHltqd();
        if (hltqd != null) {
            stmt.bindString(5, hltqd);
        }
 
        String jgzl = entity.getJgzl();
        if (jgzl != null) {
            stmt.bindString(6, jgzl);
        }
 
        String qmzl = entity.getQmzl();
        if (qmzl != null) {
            stmt.bindString(7, qmzl);
        }
 
        String xbm = entity.getXbm();
        if (xbm != null) {
            stmt.bindString(8, xbm);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ProQuality entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getRid());
 
        String gbhd = entity.getGbhd();
        if (gbhd != null) {
            stmt.bindString(3, gbhd);
        }
 
        String gjfb = entity.getGjfb();
        if (gjfb != null) {
            stmt.bindString(4, gjfb);
        }
 
        String hltqd = entity.getHltqd();
        if (hltqd != null) {
            stmt.bindString(5, hltqd);
        }
 
        String jgzl = entity.getJgzl();
        if (jgzl != null) {
            stmt.bindString(6, jgzl);
        }
 
        String qmzl = entity.getQmzl();
        if (qmzl != null) {
            stmt.bindString(7, qmzl);
        }
 
        String xbm = entity.getXbm();
        if (xbm != null) {
            stmt.bindString(8, xbm);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public ProQuality readEntity(Cursor cursor, int offset) {
        ProQuality entity = new ProQuality( //
            cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // rid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // gbhd
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // gjfb
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // hltqd
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // jgzl
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // qmzl
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // xbm
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ProQuality entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setRid(cursor.getLong(offset + 1));
        entity.setGbhd(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGjfb(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setHltqd(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setJgzl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setQmzl(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setXbm(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ProQuality entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ProQuality entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ProQuality entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
