package com.zhilian.rf_qims.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 2): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 2;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        AreaDao.createTable(db, ifNotExists);
        AreaMesDao.createTable(db, ifNotExists);
        CaConfigJsonDao.createTable(db, ifNotExists);
        CaTestJsonDao.createTable(db, ifNotExists);
        CheckUserDao.createTable(db, ifNotExists);
        CompanyDao.createTable(db, ifNotExists);
        EntEquipmentJsonDao.createTable(db, ifNotExists);
        EnterpriseCreditJsonDao.createTable(db, ifNotExists);
        EnterpriseInfoJsonDao.createTable(db, ifNotExists);
        EvaluateAddJsonDao.createTable(db, ifNotExists);
        EvaluateDeductJsonDao.createTable(db, ifNotExists);
        EvaluateStandardJsonDao.createTable(db, ifNotExists);
        EvaluateTestJsonDao.createTable(db, ifNotExists);
        InsQualityDao.createTable(db, ifNotExists);
        InsSizeDao.createTable(db, ifNotExists);
        IntegrityUserJsonDao.createTable(db, ifNotExists);
        ModelDao.createTable(db, ifNotExists);
        PersonnelJsonDao.createTable(db, ifNotExists);
        PhotoPathDao.createTable(db, ifNotExists);
        ProjectDao.createTable(db, ifNotExists);
        ProQualityDao.createTable(db, ifNotExists);
        ProSizeDao.createTable(db, ifNotExists);
        SampleDao.createTable(db, ifNotExists);
        SampleCheckDao.createTable(db, ifNotExists);
        SampleCheckAlterLogDao.createTable(db, ifNotExists);
        SampleOriginalDao.createTable(db, ifNotExists);
        SamplePageDao.createTable(db, ifNotExists);
        ScenePicDao.createTable(db, ifNotExists);
        SignPicDao.createTable(db, ifNotExists);
        UserInfoDao.createTable(db, ifNotExists);
        WorkAbilityJsonDao.createTable(db, ifNotExists);
        WorkUserJsonDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        AreaDao.dropTable(db, ifExists);
        AreaMesDao.dropTable(db, ifExists);
        CaConfigJsonDao.dropTable(db, ifExists);
        CaTestJsonDao.dropTable(db, ifExists);
        CheckUserDao.dropTable(db, ifExists);
        CompanyDao.dropTable(db, ifExists);
        EntEquipmentJsonDao.dropTable(db, ifExists);
        EnterpriseCreditJsonDao.dropTable(db, ifExists);
        EnterpriseInfoJsonDao.dropTable(db, ifExists);
        EvaluateAddJsonDao.dropTable(db, ifExists);
        EvaluateDeductJsonDao.dropTable(db, ifExists);
        EvaluateStandardJsonDao.dropTable(db, ifExists);
        EvaluateTestJsonDao.dropTable(db, ifExists);
        InsQualityDao.dropTable(db, ifExists);
        InsSizeDao.dropTable(db, ifExists);
        IntegrityUserJsonDao.dropTable(db, ifExists);
        ModelDao.dropTable(db, ifExists);
        PersonnelJsonDao.dropTable(db, ifExists);
        PhotoPathDao.dropTable(db, ifExists);
        ProjectDao.dropTable(db, ifExists);
        ProQualityDao.dropTable(db, ifExists);
        ProSizeDao.dropTable(db, ifExists);
        SampleDao.dropTable(db, ifExists);
        SampleCheckDao.dropTable(db, ifExists);
        SampleCheckAlterLogDao.dropTable(db, ifExists);
        SampleOriginalDao.dropTable(db, ifExists);
        SamplePageDao.dropTable(db, ifExists);
        ScenePicDao.dropTable(db, ifExists);
        SignPicDao.dropTable(db, ifExists);
        UserInfoDao.dropTable(db, ifExists);
        WorkAbilityJsonDao.dropTable(db, ifExists);
        WorkUserJsonDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(AreaDao.class);
        registerDaoClass(AreaMesDao.class);
        registerDaoClass(CaConfigJsonDao.class);
        registerDaoClass(CaTestJsonDao.class);
        registerDaoClass(CheckUserDao.class);
        registerDaoClass(CompanyDao.class);
        registerDaoClass(EntEquipmentJsonDao.class);
        registerDaoClass(EnterpriseCreditJsonDao.class);
        registerDaoClass(EnterpriseInfoJsonDao.class);
        registerDaoClass(EvaluateAddJsonDao.class);
        registerDaoClass(EvaluateDeductJsonDao.class);
        registerDaoClass(EvaluateStandardJsonDao.class);
        registerDaoClass(EvaluateTestJsonDao.class);
        registerDaoClass(InsQualityDao.class);
        registerDaoClass(InsSizeDao.class);
        registerDaoClass(IntegrityUserJsonDao.class);
        registerDaoClass(ModelDao.class);
        registerDaoClass(PersonnelJsonDao.class);
        registerDaoClass(PhotoPathDao.class);
        registerDaoClass(ProjectDao.class);
        registerDaoClass(ProQualityDao.class);
        registerDaoClass(ProSizeDao.class);
        registerDaoClass(SampleDao.class);
        registerDaoClass(SampleCheckDao.class);
        registerDaoClass(SampleCheckAlterLogDao.class);
        registerDaoClass(SampleOriginalDao.class);
        registerDaoClass(SamplePageDao.class);
        registerDaoClass(ScenePicDao.class);
        registerDaoClass(SignPicDao.class);
        registerDaoClass(UserInfoDao.class);
        registerDaoClass(WorkAbilityJsonDao.class);
        registerDaoClass(WorkUserJsonDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
