package com.zhilian.rf_qims.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zhilian.rf_qims.entity.EvaluateAddJson;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EVALUATE_ADD_JSON".
*/
public class EvaluateAddJsonDao extends AbstractDao<EvaluateAddJson, Long> {

    public static final String TABLENAME = "EVALUATE_ADD_JSON";

    /**
     * Properties of entity EvaluateAddJson.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Eid = new Property(1, Integer.class, "eid", false, "EID");
        public final static Property Cid = new Property(2, Integer.class, "cid", false, "CID");
        public final static Property Item = new Property(3, String.class, "item", false, "ITEM");
        public final static Property Score = new Property(4, float.class, "score", false, "SCORE");
        public final static Property GetDate = new Property(5, java.util.Date.class, "getDate", false, "GET_DATE");
        public final static Property Add_url = new Property(6, String.class, "add_url", false, "ADD_URL");
        public final static Property Status = new Property(7, Integer.class, "status", false, "STATUS");
        public final static Property Type = new Property(8, Integer.class, "type", false, "TYPE");
        public final static Property Item_name = new Property(9, String.class, "item_name", false, "ITEM_NAME");
        public final static Property Prize_unit = new Property(10, String.class, "prize_unit", false, "PRIZE_UNIT");
        public final static Property Remark = new Property(11, String.class, "remark", false, "REMARK");
    }


    public EvaluateAddJsonDao(DaoConfig config) {
        super(config);
    }
    
    public EvaluateAddJsonDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EVALUATE_ADD_JSON\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"EID\" INTEGER," + // 1: eid
                "\"CID\" INTEGER," + // 2: cid
                "\"ITEM\" TEXT," + // 3: item
                "\"SCORE\" REAL NOT NULL ," + // 4: score
                "\"GET_DATE\" INTEGER," + // 5: getDate
                "\"ADD_URL\" TEXT," + // 6: add_url
                "\"STATUS\" INTEGER," + // 7: status
                "\"TYPE\" INTEGER," + // 8: type
                "\"ITEM_NAME\" TEXT," + // 9: item_name
                "\"PRIZE_UNIT\" TEXT," + // 10: prize_unit
                "\"REMARK\" TEXT);"); // 11: remark
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EVALUATE_ADD_JSON\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, EvaluateAddJson entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer eid = entity.getEid();
        if (eid != null) {
            stmt.bindLong(2, eid);
        }
 
        Integer cid = entity.getCid();
        if (cid != null) {
            stmt.bindLong(3, cid);
        }
 
        String item = entity.getItem();
        if (item != null) {
            stmt.bindString(4, item);
        }
        stmt.bindDouble(5, entity.getScore());
 
        java.util.Date getDate = entity.getGetDate();
        if (getDate != null) {
            stmt.bindLong(6, getDate.getTime());
        }
 
        String add_url = entity.getAdd_url();
        if (add_url != null) {
            stmt.bindString(7, add_url);
        }
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(8, status);
        }
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(9, type);
        }
 
        String item_name = entity.getItem_name();
        if (item_name != null) {
            stmt.bindString(10, item_name);
        }
 
        String prize_unit = entity.getPrize_unit();
        if (prize_unit != null) {
            stmt.bindString(11, prize_unit);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(12, remark);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, EvaluateAddJson entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer eid = entity.getEid();
        if (eid != null) {
            stmt.bindLong(2, eid);
        }
 
        Integer cid = entity.getCid();
        if (cid != null) {
            stmt.bindLong(3, cid);
        }
 
        String item = entity.getItem();
        if (item != null) {
            stmt.bindString(4, item);
        }
        stmt.bindDouble(5, entity.getScore());
 
        java.util.Date getDate = entity.getGetDate();
        if (getDate != null) {
            stmt.bindLong(6, getDate.getTime());
        }
 
        String add_url = entity.getAdd_url();
        if (add_url != null) {
            stmt.bindString(7, add_url);
        }
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(8, status);
        }
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(9, type);
        }
 
        String item_name = entity.getItem_name();
        if (item_name != null) {
            stmt.bindString(10, item_name);
        }
 
        String prize_unit = entity.getPrize_unit();
        if (prize_unit != null) {
            stmt.bindString(11, prize_unit);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(12, remark);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public EvaluateAddJson readEntity(Cursor cursor, int offset) {
        EvaluateAddJson entity = new EvaluateAddJson( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // eid
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // cid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // item
            cursor.getFloat(offset + 4), // score
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // getDate
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // add_url
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // status
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // type
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // item_name
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // prize_unit
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11) // remark
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, EvaluateAddJson entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEid(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setCid(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setItem(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setScore(cursor.getFloat(offset + 4));
        entity.setGetDate(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setAdd_url(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setStatus(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setType(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setItem_name(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setPrize_unit(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setRemark(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(EvaluateAddJson entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(EvaluateAddJson entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(EvaluateAddJson entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
