package com.zhilian.rf_qims.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zhilian.rf_qims.entity.IntegrityUserJson;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INTEGRITY_USER_JSON".
*/
public class IntegrityUserJsonDao extends AbstractDao<IntegrityUserJson, Long> {

    public static final String TABLENAME = "INTEGRITY_USER_JSON";

    /**
     * Properties of entity IntegrityUserJson.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Dlid = new Property(2, String.class, "dlid", false, "DLID");
        public final static Property Pwd1 = new Property(3, String.class, "pwd1", false, "PWD1");
        public final static Property Pwd2 = new Property(4, String.class, "pwd2", false, "PWD2");
    }


    public IntegrityUserJsonDao(DaoConfig config) {
        super(config);
    }
    
    public IntegrityUserJsonDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INTEGRITY_USER_JSON\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"DLID\" TEXT," + // 2: dlid
                "\"PWD1\" TEXT," + // 3: pwd1
                "\"PWD2\" TEXT);"); // 4: pwd2
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INTEGRITY_USER_JSON\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, IntegrityUserJson entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String dlid = entity.getDlid();
        if (dlid != null) {
            stmt.bindString(3, dlid);
        }
 
        String pwd1 = entity.getPwd1();
        if (pwd1 != null) {
            stmt.bindString(4, pwd1);
        }
 
        String pwd2 = entity.getPwd2();
        if (pwd2 != null) {
            stmt.bindString(5, pwd2);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, IntegrityUserJson entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String dlid = entity.getDlid();
        if (dlid != null) {
            stmt.bindString(3, dlid);
        }
 
        String pwd1 = entity.getPwd1();
        if (pwd1 != null) {
            stmt.bindString(4, pwd1);
        }
 
        String pwd2 = entity.getPwd2();
        if (pwd2 != null) {
            stmt.bindString(5, pwd2);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public IntegrityUserJson readEntity(Cursor cursor, int offset) {
        IntegrityUserJson entity = new IntegrityUserJson( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // dlid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // pwd1
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // pwd2
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, IntegrityUserJson entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDlid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPwd1(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPwd2(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(IntegrityUserJson entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(IntegrityUserJson entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(IntegrityUserJson entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
