package com.zhilian.rf_qims.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zhilian.rf_qims.entity.WorkUserJson;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WORK_USER_JSON".
*/
public class WorkUserJsonDao extends AbstractDao<WorkUserJson, Long> {

    public static final String TABLENAME = "WORK_USER_JSON";

    /**
     * Properties of entity WorkUserJson.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, Long.class, "ID", true, "_id");
        public final static Property NAME = new Property(1, String.class, "NAME", false, "NAME");
        public final static Property DLID = new Property(2, String.class, "DLID", false, "DLID");
        public final static Property PWD = new Property(3, String.class, "PWD", false, "PWD");
    }


    public WorkUserJsonDao(DaoConfig config) {
        super(config);
    }
    
    public WorkUserJsonDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WORK_USER_JSON\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: ID
                "\"NAME\" TEXT," + // 1: NAME
                "\"DLID\" TEXT," + // 2: DLID
                "\"PWD\" TEXT);"); // 3: PWD
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WORK_USER_JSON\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WorkUserJson entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
 
        String NAME = entity.getNAME();
        if (NAME != null) {
            stmt.bindString(2, NAME);
        }
 
        String DLID = entity.getDLID();
        if (DLID != null) {
            stmt.bindString(3, DLID);
        }
 
        String PWD = entity.getPWD();
        if (PWD != null) {
            stmt.bindString(4, PWD);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WorkUserJson entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
 
        String NAME = entity.getNAME();
        if (NAME != null) {
            stmt.bindString(2, NAME);
        }
 
        String DLID = entity.getDLID();
        if (DLID != null) {
            stmt.bindString(3, DLID);
        }
 
        String PWD = entity.getPWD();
        if (PWD != null) {
            stmt.bindString(4, PWD);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public WorkUserJson readEntity(Cursor cursor, int offset) {
        WorkUserJson entity = new WorkUserJson( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // NAME
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // DLID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // PWD
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WorkUserJson entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNAME(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDLID(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPWD(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(WorkUserJson entity, long rowId) {
        entity.setID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(WorkUserJson entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WorkUserJson entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
